---
title: "Plotting Excercise 1"
author: "MRC LMS"
date: "19/09/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

These exercises cover the sections of Plotting in R [PlottingInR](https://lmsbioinformatics.github.io/LMS_Reproducible-R/r_course/introToR_Session1.html).



## Exercise 1

Please load the dateset **mtcars** by calling data(mtcars) and use the base R graphics to 

(1) create a scatter plot of mtcars\$mpg VS mtcars\$wt (x-axis = mpg and y-axis = wt). 

(2) change the labels for x axis = "Miles/(US) gallon" and y axis = "Weight (1000 lbs)"

(3) add title = "scatter plot"

(4) change the colour of points to red and the the shape of points to "filled circle"

[hint: use data() function to load mtcars]

```{r,echo=T,eval=F}
data(mtcars)
head(mtcars)
```


## Exercise 2

Please load the dateset **mtcars** by calling data(mtcars) and use the ggplot2 to 

(1) create a scatter plot of mtcars\$mpg VS mtcars\$wt (x-axis = mpg and y-axis = wt).

(2) change the labels for x axis = "Miles/(US) gallon" and y axis = "Weight (1000 lbs)"

(3) add title = "scatter plot"

(4) change the colour of points to red [hint: use col="red" when constructing aesthetic mappings]

(5) a. what will happen if change the colour of points to mtcars\$am [hint: use col=am when constructing aesthetic mappings]

    b. what will happen if change the colour of points use col=as.factor(am) when constructing aesthetic mappings



